import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "../components/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import JotaiProvider from "@/components/providers/jotai-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${font.className} antialiased h-screen w-full`}>
          <JotaiProvider>
            <ThemeProvider attribute="class" defaultTheme="dark">
              {children}
              <Toaster richColors position="bottom-left" expand />
            </ThemeProvider>
          </JotaiProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
